// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFms9IxzfEbu50yj5IM-_y9NaLpr5JoT4',
    appId: '1:250508813798:web:c7b2152b5616449b376227',
    messagingSenderId: '250508813798',
    projectId: 'smartpantry-91bf8',
    authDomain: 'smartpantry-91bf8.firebaseapp.com',
    storageBucket: 'smartpantry-91bf8.firebasestorage.app',
    measurementId: 'G-DWMHJML5B5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDw_Ep8r82TQqGlBtAzdmdqLZCGvE7rtcY',
    appId: '1:250508813798:android:95df69469a3462ef376227',
    messagingSenderId: '250508813798',
    projectId: 'smartpantry-91bf8',
    storageBucket: 'smartpantry-91bf8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSA7u37cpizIv3a_pZljjiDhG7yMZ1al4',
    appId: '1:250508813798:ios:d25db7ce719215d7376227',
    messagingSenderId: '250508813798',
    projectId: 'smartpantry-91bf8',
    storageBucket: 'smartpantry-91bf8.firebasestorage.app',
    iosBundleId: 'com.example.smartPantry',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSA7u37cpizIv3a_pZljjiDhG7yMZ1al4',
    appId: '1:250508813798:ios:d25db7ce719215d7376227',
    messagingSenderId: '250508813798',
    projectId: 'smartpantry-91bf8',
    storageBucket: 'smartpantry-91bf8.firebasestorage.app',
    iosBundleId: 'com.example.smartPantry',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFms9IxzfEbu50yj5IM-_y9NaLpr5JoT4',
    appId: '1:250508813798:web:2237f702ee92791f376227',
    messagingSenderId: '250508813798',
    projectId: 'smartpantry-91bf8',
    authDomain: 'smartpantry-91bf8.firebaseapp.com',
    storageBucket: 'smartpantry-91bf8.firebasestorage.app',
    measurementId: 'G-XMS154GN54',
  );
}
